name: webview
description: A Flutter project to manage a webview.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  webview_flutter: ^3.0.4
  webview_flutter_plus: ^0.3.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/use_case_1/
    - assets/use_case_2/